name: GitActions Demo
on: [push] # what event does this workflow run with?


env:
 GLOBAL_VAR: "This is public!"


env:
 SECRET_TEXT: ${{ secrets.SUPER_SECRET_TEXT }}


jobs:
  action_demo:
    # runs-on is what type of OS is our pipeline running on
   runs-on: ubuntu-latest
    # what do I want the job to do?
   steps:
   - run: echo "Hello World!"
   - run: pwd
   - run: ls
   - run: echo 'Job Status is ${{job.status}}'

#this code focuses on cloning my repo

  clone_demo:
   runs-on: ubuntu-latest
   steps:
    - name: Check Out Repo...
      uses: actions/checkout@v3
    - name: List Contents of Current Directory..
      run: ls -al
    - name: Run a python script
      run: python script.py

  bash_demo:
   runs-on: ubuntu-latest
   steps:
   - name: Check Out Repo...
     uses: actions/checkout@v3
   - name: List Contents of Current Directory..
     run: ls -al
   - name: Run a bash script
     run: bash script.sh

  variable_job:
   runs-on: ubuntu-latest
   steps:
   - name: Printing Global Varaible...
     run: echo $GLOBAL_VAR
   - name: Printing Secret Text...
     run: $SECRET_TEXT

  


   
